#include "camera_bridge_mcap/recorder.hpp"
#include <cstring>
#include <cmath>
#include <map>
#include <mcap/writer.hpp>
#include "camera_bridge_mcap/ros2_messages.hpp"
#include "camera_bridge_core/stream_names.hpp"
#include "live_sink.hpp"

namespace camera_bridge_mcap { namespace {
struct Out { mcap::Schema schema; mcap::Channel channel; std::string schemaText; uint32_t sequence=0; };
Out makeChannel(const char* topic,const char* type,const std::string& text){Out o;o.schema.name=type;o.schema.encoding="ros2msg";o.schemaText=text;o.schema.data.resize(text.size());std::memcpy(o.schema.data.data(),text.data(),text.size());o.channel.topic=topic;o.channel.messageEncoding="cdr";return o;}
std::vector<uint8_t> bytes(const cv::Mat&m){cv::Mat c=m.isContinuous()?m:m.clone();return{c.data,c.data+c.total()*c.elemSize()};}
TimingMessage timing(uint8_t kind,uint32_t source,uint64_t host,uint64_t device,const bridge::FrameTiming&t,const std::string&frame){TimingMessage m;m.header={rosTimeFromUs(host),frame};m.source_id=source;m.stream_kind=kind;m.host_timestamp_us=host;m.device_timestamp_us=device;m.driver_receive_steady_us=t.driver_receive_steady_us;m.capture_steady_us=t.capture_steady_us;m.capture_steady_valid=t.capture_steady_valid;m.timestamp_source=static_cast<uint8_t>(t.timestamp_source);m.clock_mapping_uncertainty_us=t.clock_mapping_uncertainty_us;return m;}
CameraInfoMessage info(const bridge::CameraIntrinsic&i,const bridge::CameraDistortion&d,uint64_t ts,const std::string&frame){CameraInfoMessage m;m.header={rosTimeFromUs(ts),frame};m.width=i.width;m.height=i.height;m.distortion_model=distortionModelName(d.model);m.d={d.k1,d.k2,d.p1,d.p2,d.k3,d.k4,d.k5,d.k6};m.k={i.fx,0,i.cx,0,i.fy,i.cy,0,0,1};m.p={i.fx,0,i.cx,0,0,i.fy,i.cy,0,0,0,1,0};return m;}
std::array<double,4> quaternion(const float*r){std::array<double,4>q{};const double trace=r[0]+r[4]+r[8];if(trace>0){const double s=std::sqrt(trace+1.0)*2;q={(r[7]-r[5])/s,(r[2]-r[6])/s,(r[3]-r[1])/s,.25*s};}else if(r[0]>r[4]&&r[0]>r[8]){const double s=std::sqrt(1.0+r[0]-r[4]-r[8])*2;q={.25*s,(r[1]+r[3])/s,(r[2]+r[6])/s,(r[7]-r[5])/s};}else if(r[4]>r[8]){const double s=std::sqrt(1.0+r[4]-r[0]-r[8])*2;q={(r[1]+r[3])/s,.25*s,(r[5]+r[7])/s,(r[2]-r[6])/s};}else{const double s=std::sqrt(1.0+r[8]-r[0]-r[4])*2;q={(r[2]+r[6])/s,(r[5]+r[7])/s,.25*s,(r[3]-r[1])/s};}return q;}
}
class Ros2McapRecorder::Impl { public:
 enum class Stream {Color,Depth,Imu,ColorInfo,DepthInfo};
 struct SourceChannels {Out color,depth,imu,colorInfo,depthInfo;explicit SourceChannels(uint32_t id):color(makeChannel((bridge::cameraTopicPrefix(id)+"/color/image_raw").c_str(),"sensor_msgs/msg/Image",imageSchema())),depth(makeChannel((bridge::cameraTopicPrefix(id)+"/depth/image_raw").c_str(),"sensor_msgs/msg/Image",imageSchema())),imu(makeChannel((bridge::cameraTopicPrefix(id)+"/imu/data_raw").c_str(),"sensor_msgs/msg/Imu",imuSchema())),colorInfo(makeChannel((bridge::cameraTopicPrefix(id)+"/color/camera_info").c_str(),"sensor_msgs/msg/CameraInfo",cameraInfoSchema())),depthInfo(makeChannel((bridge::cameraTopicPrefix(id)+"/depth/camera_info").c_str(),"sensor_msgs/msg/CameraInfo",cameraInfoSchema())){}};
 explicit Impl(Options o):options(std::move(o)),timingCh(makeChannel("/amr/camera_timing","camera_bridge_msgs/msg/FrameTiming",timingSchema())),tfStatic(makeChannel("/tf_static","tf2_msgs/msg/TFMessage",tfSchema())){}
 void add(Out&c){c.schema.data.resize(c.schemaText.size());std::memcpy(c.schema.data.data(),c.schemaText.data(),c.schemaText.size());writer.addSchema(c.schema);c.channel.schemaId=c.schema.id;writer.addChannel(c.channel);}
 bool open(std::string*error){std::lock_guard<std::mutex>l(mu);if(active)return true;std::error_code ec;if(!options.output_path.parent_path().empty())std::filesystem::create_directories(options.output_path.parent_path(),ec);if(ec){if(error)*error=ec.message();return false;}mcap::McapWriterOptions o("ros2");o.chunkSize=options.chunk_size_bytes;o.compression=options.use_zstd?mcap::Compression::Zstd:mcap::Compression::None;auto s=writer.open(options.output_path.string(),o);if(!s.ok()){if(error)*error=s.message;return false;}add(timingCh);add(tfStatic);if(options.live_publish_enabled){live=createLiveSink();std::string liveError;if(!live->start(options.live_publish_host,options.live_publish_port,liveError)){live.reset();if(options.live_publish_required){writer.close();if(error)*error="failed to start Foxglove live sink: "+liveError;return false;}lastLiveError=liveError;}}active=true;return true;}
 void close(){std::lock_guard<std::mutex>l(mu);if(live){live->stop();live.reset();}if(active){writer.close();active=false;}sources.clear();}
 void emit(Out&c,const std::vector<uint8_t>&data,uint64_t us){mcap::Message m;m.channelId=c.channel.id;m.sequence=c.sequence++;m.logTime=us*1000;m.publishTime=us*1000;m.data=reinterpret_cast<const std::byte*>(data.data());m.dataSize=data.size();writer.write(m);if(live){std::string liveError;if(!live->publish(c.channel.topic,c.schema.name,c.schemaText,data,us*1000,liveError))lastLiveError=liveError;}}
 SourceChannels& source(uint32_t id){auto [it,inserted]=sources.try_emplace(id,id);if(inserted){add(it->second.color);add(it->second.depth);add(it->second.imu);add(it->second.colorInfo);add(it->second.depthInfo);}return it->second;}
 void write(uint32_t id,Stream stream,const std::vector<uint8_t>&data,uint64_t us){std::lock_guard<std::mutex>l(mu);if(!active)return;auto&s=source(id);Out*c=stream==Stream::Color?&s.color:stream==Stream::Depth?&s.depth:stream==Stream::Imu?&s.imu:stream==Stream::ColorInfo?&s.colorInfo:&s.depthInfo;emit(*c,data,us);}
 void writeGlobal(Out&c,const std::vector<uint8_t>&data,uint64_t us){std::lock_guard<std::mutex>l(mu);if(active)emit(c,data,us);}
 Options options;mutable std::mutex mu;mcap::McapWriter writer;bool active=false;std::map<uint32_t,SourceChannels>sources;Out timingCh,tfStatic;std::unique_ptr<LiveSink>live;std::string lastLiveError;
};
Ros2McapRecorder::Ros2McapRecorder(Options o):impl_(std::make_unique<Impl>(std::move(o))){} Ros2McapRecorder::~Ros2McapRecorder(){stop();}
bool Ros2McapRecorder::start(std::string*e){return impl_->open(e);}void Ros2McapRecorder::stop(){impl_->close();}bool Ros2McapRecorder::running()const{std::lock_guard<std::mutex>l(impl_->mu);return impl_->active;}
void Ros2McapRecorder::onColorFrame(const bridge::ColorFrameEvent&e){const auto frame=bridge::cameraColorOpticalFrame(e.source_id);if(impl_->options.write_timing_metadata)impl_->writeGlobal(impl_->timingCh,encode(timing(1,e.source_id,e.timestamp_us,e.device_timestamp_us,e.timing,frame)),e.timestamp_us);ImageMessage m;m.header={rosTimeFromUs(e.timestamp_us),frame};m.height=e.bgr.rows;m.width=e.bgr.cols;m.encoding="bgr8";m.step=e.bgr.cols*3;m.data=bytes(e.bgr);impl_->write(e.source_id,Impl::Stream::Color,encode(m),e.timestamp_us);}
void Ros2McapRecorder::onDepthFrame(const bridge::DepthFrameEvent&e){const auto frame=bridge::cameraDepthOpticalFrame(e.source_id);if(impl_->options.write_timing_metadata)impl_->writeGlobal(impl_->timingCh,encode(timing(2,e.source_id,e.timestamp_us,e.device_timestamp_us,e.timing,frame)),e.timestamp_us);ImageMessage m;m.header={rosTimeFromUs(e.timestamp_us),frame};m.height=e.depth_mono16.rows;m.width=e.depth_mono16.cols;m.encoding="16UC1";m.step=e.depth_mono16.cols*2;m.data=bytes(e.depth_mono16);impl_->write(e.source_id,Impl::Stream::Depth,encode(m),e.timestamp_us);}
void Ros2McapRecorder::onImuSample(const bridge::ImuSampleEvent&e){const auto frame=bridge::cameraImuFrame(e.source_id);if(impl_->options.write_timing_metadata)impl_->writeGlobal(impl_->timingCh,encode(timing(3,e.source_id,e.timestamp_us,e.device_timestamp_us,e.timing,frame)),e.timestamp_us);ImuMessage m;m.header={rosTimeFromUs(e.timestamp_us),frame};if(e.has_gyro)m.angular_velocity={e.gyro.x,e.gyro.y,e.gyro.z};if(e.has_accel)m.linear_acceleration={e.accel.x,e.accel.y,e.accel.z};impl_->write(e.source_id,Impl::Stream::Imu,encode(m),e.timestamp_us);}
void Ros2McapRecorder::onExtrinsics(const bridge::ExtrinsicsEvent&e){TfMessage m;for(const auto&x:e.transforms){TransformStampedMessage t;t.header={rosTimeFromUs(e.timestamp_us),x.parent_frame_id};t.child_frame_id=x.child_frame_id;const double scale=x.extrinsic.translation_scale_to_meters;t.translation={x.extrinsic.trans[0]*scale,x.extrinsic.trans[1]*scale,x.extrinsic.trans[2]*scale};t.rotation=quaternion(x.extrinsic.rot);m.transforms.push_back(std::move(t));}impl_->writeGlobal(impl_->tfStatic,encode(m),e.timestamp_us);}
void Ros2McapRecorder::onCameraCalibration(const bridge::CameraCalibrationEvent&e){if(e.has_color)impl_->write(e.source_id,Impl::Stream::ColorInfo,encode(info(e.color_intrinsic,e.color_distortion,e.timestamp_us,bridge::cameraColorOpticalFrame(e.source_id))),e.timestamp_us);if(e.has_depth)impl_->write(e.source_id,Impl::Stream::DepthInfo,encode(info(e.depth_intrinsic,e.depth_distortion,e.timestamp_us,bridge::cameraDepthOpticalFrame(e.source_id))),e.timestamp_us);}
} // namespace camera_bridge_mcap
