#include "camera_bridge_mcap/ros2_messages.hpp"
#include "camera_bridge_mcap/cdr.hpp"
#include <limits>
#include <stdexcept>

namespace camera_bridge_mcap { namespace {
void wh(CdrWriter&w,const Header&h){w.primitive<int32_t>(h.stamp.sec);w.primitive<uint32_t>(h.stamp.nanosec);w.string(h.frame_id);}
Header rh(CdrReader&r){Header h;h.stamp.sec=r.primitive<int32_t>();h.stamp.nanosec=r.primitive<uint32_t>();h.frame_id=r.string();return h;}
void wv(CdrWriter&w,const std::vector<double>&v){w.primitive<uint32_t>(static_cast<uint32_t>(v.size()));w.fixedDoubles(v.data(),v.size());}
std::vector<double> rv(CdrReader&r){std::vector<double>v(r.primitive<uint32_t>());r.fixedDoubles(v.data(),v.size());return v;}
}
RosTime rosTimeFromUs(uint64_t us){auto s=us/1000000;if(s>static_cast<uint64_t>(INT32_MAX))throw std::overflow_error("ROS time overflow");return{static_cast<int32_t>(s),static_cast<uint32_t>(us%1000000*1000)};}
uint64_t timestampUs(const RosTime&t){if(t.sec<0)throw std::runtime_error("negative ROS time");return static_cast<uint64_t>(t.sec)*1000000+t.nanosec/1000;}
std::vector<uint8_t> encode(const ImageMessage&m){CdrWriter w;wh(w,m.header);w.primitive<uint32_t>(m.height);w.primitive<uint32_t>(m.width);w.string(m.encoding);w.boolean(m.is_bigendian);w.primitive<uint32_t>(m.step);w.bytes(m.data.data(),m.data.size());return w.take();}
ImageMessage decodeImage(const uint8_t*p,size_t n){CdrReader r(p,n);ImageMessage m;m.header=rh(r);m.height=r.primitive<uint32_t>();m.width=r.primitive<uint32_t>();m.encoding=r.string();m.is_bigendian=r.boolean();m.step=r.primitive<uint32_t>();m.data=r.bytes();return m;}
std::vector<uint8_t> encode(const ImuMessage&m){CdrWriter w;wh(w,m.header);w.fixedDoubles(m.orientation.data(),4);w.fixedDoubles(m.orientation_covariance.data(),9);w.fixedDoubles(m.angular_velocity.data(),3);w.fixedDoubles(m.angular_velocity_covariance.data(),9);w.fixedDoubles(m.linear_acceleration.data(),3);w.fixedDoubles(m.linear_acceleration_covariance.data(),9);return w.take();}
ImuMessage decodeImu(const uint8_t*p,size_t n){CdrReader r(p,n);ImuMessage m;m.header=rh(r);r.fixedDoubles(m.orientation.data(),4);r.fixedDoubles(m.orientation_covariance.data(),9);r.fixedDoubles(m.angular_velocity.data(),3);r.fixedDoubles(m.angular_velocity_covariance.data(),9);r.fixedDoubles(m.linear_acceleration.data(),3);r.fixedDoubles(m.linear_acceleration_covariance.data(),9);return m;}
std::vector<uint8_t> encode(const CameraInfoMessage&m){CdrWriter w;wh(w,m.header);w.primitive<uint32_t>(m.height);w.primitive<uint32_t>(m.width);w.string(m.distortion_model);wv(w,m.d);w.fixedDoubles(m.k.data(),9);w.fixedDoubles(m.r.data(),9);w.fixedDoubles(m.p.data(),12);w.primitive<uint32_t>(m.binning_x);w.primitive<uint32_t>(m.binning_y);w.primitive<uint32_t>(m.roi_x_offset);w.primitive<uint32_t>(m.roi_y_offset);w.primitive<uint32_t>(m.roi_height);w.primitive<uint32_t>(m.roi_width);w.boolean(m.roi_do_rectify);return w.take();}
CameraInfoMessage decodeCameraInfo(const uint8_t*p,size_t n){CdrReader r(p,n);CameraInfoMessage m;m.header=rh(r);m.height=r.primitive<uint32_t>();m.width=r.primitive<uint32_t>();m.distortion_model=r.string();m.d=rv(r);r.fixedDoubles(m.k.data(),9);r.fixedDoubles(m.r.data(),9);r.fixedDoubles(m.p.data(),12);m.binning_x=r.primitive<uint32_t>();m.binning_y=r.primitive<uint32_t>();m.roi_x_offset=r.primitive<uint32_t>();m.roi_y_offset=r.primitive<uint32_t>();m.roi_height=r.primitive<uint32_t>();m.roi_width=r.primitive<uint32_t>();m.roi_do_rectify=r.boolean();return m;}
std::vector<uint8_t> encode(const TimingMessage&m){CdrWriter w;wh(w,m.header);w.primitive<uint32_t>(m.source_id);w.primitive<uint8_t>(m.stream_kind);w.primitive<uint64_t>(m.host_timestamp_us);w.primitive<uint64_t>(m.device_timestamp_us);w.primitive<uint64_t>(m.driver_receive_steady_us);w.primitive<uint64_t>(m.capture_steady_us);w.boolean(m.capture_steady_valid);w.primitive<uint8_t>(m.timestamp_source);w.primitive<double>(m.clock_mapping_uncertainty_us);return w.take();}
TimingMessage decodeTiming(const uint8_t*p,size_t n){CdrReader r(p,n);TimingMessage m;m.header=rh(r);m.source_id=r.primitive<uint32_t>();m.stream_kind=r.primitive<uint8_t>();m.host_timestamp_us=r.primitive<uint64_t>();m.device_timestamp_us=r.primitive<uint64_t>();m.driver_receive_steady_us=r.primitive<uint64_t>();m.capture_steady_us=r.primitive<uint64_t>();m.capture_steady_valid=r.boolean();m.timestamp_source=r.primitive<uint8_t>();m.clock_mapping_uncertainty_us=r.primitive<double>();return m;}
std::vector<uint8_t> encode(const TfMessage&m){CdrWriter w;w.primitive<uint32_t>(static_cast<uint32_t>(m.transforms.size()));for(const auto&t:m.transforms){wh(w,t.header);w.string(t.child_frame_id);w.fixedDoubles(t.translation.data(),3);w.fixedDoubles(t.rotation.data(),4);}return w.take();}
TfMessage decodeTf(const uint8_t*p,size_t n){CdrReader r(p,n);TfMessage m;m.transforms.resize(r.primitive<uint32_t>());for(auto&t:m.transforms){t.header=rh(r);t.child_frame_id=r.string();r.fixedDoubles(t.translation.data(),3);r.fixedDoubles(t.rotation.data(),4);}return m;}
std::string distortionModelName(bridge::CameraDistortionModel m){return m==bridge::CameraDistortionModel::None?"":m==bridge::CameraDistortionModel::KannalaBrandt4?"equidistant":"plumb_bob";}
const std::string& imageSchema(){static const std::string s="std_msgs/Header header\nuint32 height\nuint32 width\nstring encoding\nuint8 is_bigendian\nuint32 step\nuint8[] data\n================================================================================\nMSG: std_msgs/Header\nbuiltin_interfaces/Time stamp\nstring frame_id\n================================================================================\nMSG: builtin_interfaces/Time\nint32 sec\nuint32 nanosec\n";return s;}
const std::string& imuSchema(){static const std::string s="std_msgs/Header header\ngeometry_msgs/Quaternion orientation\nfloat64[9] orientation_covariance\ngeometry_msgs/Vector3 angular_velocity\nfloat64[9] angular_velocity_covariance\ngeometry_msgs/Vector3 linear_acceleration\nfloat64[9] linear_acceleration_covariance\n================================================================================\nMSG: std_msgs/Header\nbuiltin_interfaces/Time stamp\nstring frame_id\n================================================================================\nMSG: builtin_interfaces/Time\nint32 sec\nuint32 nanosec\n================================================================================\nMSG: geometry_msgs/Quaternion\nfloat64 x\nfloat64 y\nfloat64 z\nfloat64 w\n================================================================================\nMSG: geometry_msgs/Vector3\nfloat64 x\nfloat64 y\nfloat64 z\n";return s;}
const std::string& cameraInfoSchema(){static const std::string s="std_msgs/Header header\nuint32 height\nuint32 width\nstring distortion_model\nfloat64[] d\nfloat64[9] k\nfloat64[9] r\nfloat64[12] p\nuint32 binning_x\nuint32 binning_y\nsensor_msgs/RegionOfInterest roi\n================================================================================\nMSG: std_msgs/Header\nbuiltin_interfaces/Time stamp\nstring frame_id\n================================================================================\nMSG: builtin_interfaces/Time\nint32 sec\nuint32 nanosec\n================================================================================\nMSG: sensor_msgs/RegionOfInterest\nuint32 x_offset\nuint32 y_offset\nuint32 height\nuint32 width\nbool do_rectify\n";return s;}
const std::string& timingSchema(){static const std::string s="std_msgs/Header header\nuint32 source_id\nuint8 stream_kind\nuint64 host_timestamp_us\nuint64 device_timestamp_us\nuint64 driver_receive_steady_us\nuint64 capture_steady_us\nbool capture_steady_valid\nuint8 timestamp_source\nfloat64 clock_mapping_uncertainty_us\n================================================================================\nMSG: std_msgs/Header\nbuiltin_interfaces/Time stamp\nstring frame_id\n================================================================================\nMSG: builtin_interfaces/Time\nint32 sec\nuint32 nanosec\n";return s;}
const std::string& tfSchema(){static const std::string s="geometry_msgs/TransformStamped[] transforms\n================================================================================\nMSG: geometry_msgs/TransformStamped\nstd_msgs/Header header\nstring child_frame_id\ngeometry_msgs/Transform transform\n================================================================================\nMSG: std_msgs/Header\nbuiltin_interfaces/Time stamp\nstring frame_id\n================================================================================\nMSG: builtin_interfaces/Time\nint32 sec\nuint32 nanosec\n================================================================================\nMSG: geometry_msgs/Transform\ngeometry_msgs/Vector3 translation\ngeometry_msgs/Quaternion rotation\n================================================================================\nMSG: geometry_msgs/Vector3\nfloat64 x\nfloat64 y\nfloat64 z\n================================================================================\nMSG: geometry_msgs/Quaternion\nfloat64 x\nfloat64 y\nfloat64 z\nfloat64 w\n";return s;}
} // namespace camera_bridge_mcap
